# Welcome to Serverless!

service: ${self:custom.serverlessStackName}

app: ${self:custom.serverlessStackName}
org: ahmedalimsoliman

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: default
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xxxx:*
      Resource: "*"

custom:
  serverlessStackName: serverless-clean-xxxxxx

functions:
  xx:
    handler: lambdas/endpoints/xx.handler
    events:
      - http:
          path: xx
          method: POST
          cors: true
