# Welcome to Serverless!

service: ${self:custom.serverlessStackName}

app: serverless-comperhend
org: ahmedalimsoliman

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: default
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - comprehend:*
      Resource: "*"

custom:
  serverlessStackName: serverless-comperhend

functions:
  analyse:
    handler: lambdas/endpoints/analyse.handler
    events:
      - http:
          path: analyse
          method: POST
          cors: true
