service: image-conversion-3

provider:
  name: aws
  runtime: python3.8
  region: me-central-1
  stage: ${opt:stage, 'dev'}
  environment:
    OUTPUT_BUCKET: ${self:custom.outputBucket}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: arn:aws:s3:::${self:custom.inputBucket}/*

    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::${self:custom.outputBucket}/*

functions:
  deleteObjectsWithTrigger:
    handler: functions/delete_object_upload_trigger.handler
    events:
      - s3:
          bucket: ${self:custom.inputBucket}
          event: s3:ObjectRemoved:*
          rules:
            - prefix: ""
            - suffix: ""
  copyObjectsWithTrigger:
    handler: functions/copy_object_upload_trigger.handler
    events:
      - s3:
          bucket: ${self:custom.inputBucket}
          event: s3:ObjectCreated:*
  # copyExistingObjects:
  #   handler: functions/copy_existing_objects.handler
  #   events:
  #     - s3:
  #         bucket: ${self:custom.inputBucket}
  #         event: s3:ObjectCreated:*
resources:
  Resources:
    OutputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.outputBucket}

custom:
  inputBucket: xsource.ahmedalimsoliman.click
  outputBucket: xdest.ahmedalimsoliman.click
