# Welcome to Serverless!

service: serverless-framework-send-sms-text
# app and org for use with dashboard.serverless.com
app: serverless-framework-send-sms-text
org: ahmedalimsoliman

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: default
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:SetSMSAttributes
        - sns:Publish
      Resource: "*"

functions:
  sendSMS:
    handler: lambdas/endpoints/sendSMS.handler
    events:
      - http:
          path: send-sms
          method: POST
          cors: true
          private: false
